name: friendlychat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

